"""Initial migration

Revision ID: 8b943a8c274d
Revises: 
Create Date: 2025-09-02 10:10:54.276485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b943a8c274d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_bid'), ['bid'], unique=True)

    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('teacher', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classrooms_code'), ['code'], unique=True)

    op.create_table('labs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labs_code'), ['code'], unique=True)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('fingerprint', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_sid'), ['sid'], unique=True)

    op.create_table('attendance_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('date_', sa.Date(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classrooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_sessions_date_'), ['date_'], unique=False)

    op.create_table('borrows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_sid', sa.String(length=32), nullable=False),
    sa.Column('book_bid', sa.String(length=32), nullable=False),
    sa.Column('borrow_dt', sa.DateTime(), nullable=True),
    sa.Column('due_dt', sa.DateTime(), nullable=False),
    sa.Column('return_dt', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['book_bid'], ['books.bid'], ),
    sa.ForeignKeyConstraint(['student_sid'], ['students.sid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hostel_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gate', sa.String(length=80), nullable=True),
    sa.Column('student_sid', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_sid'], ['students.sid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hostel_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hostel_logs_ts'), ['ts'], unique=False)

    op.create_table('lab_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('student_sid', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['student_sid'], ['students.sid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_logs_ts'), ['ts'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_sid', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('present', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_sid'], ['students.sid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_sid', name='uq_session_student')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_records')
    with op.batch_alter_table('lab_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_logs_ts'))

    op.drop_table('lab_logs')
    with op.batch_alter_table('hostel_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hostel_logs_ts'))

    op.drop_table('hostel_logs')
    op.drop_table('borrows')
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_date_'))

    op.drop_table('attendance_sessions')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_sid'))

    op.drop_table('students')
    with op.batch_alter_table('labs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labs_code'))

    op.drop_table('labs')
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classrooms_code'))

    op.drop_table('classrooms')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_bid'))

    op.drop_table('books')
    # ### end Alembic commands ###
